spring.application.name=Freelancer


spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false


# mail.smtp.host=smtp.gmail.com
# mail.smtp.port=587
# mail.smtp.username=team.nexlancer@gmail.com
# mail.smtp.password=your-app-password

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=team.nexlancer@gmail.com
spring.mail.password=zmug kjpu evir kxxy
mail.from=team.nexlancer@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# Razorpay Configuration (Test Mode)
razorpay.key.id=rzp_test_SqD4PaFVIPho06
razorpay.key.secret=vFHAC7oamBr4Tt8C1bzNEx6N